
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yeet
      PG_DATA: "/var/lib/pg_data"
    ports:
      - "5438:5432"
    networks:
      - local
networks:
  local: